name: Build Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag/branch
        id: tag
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        shell: bash
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: win64_msvc2019_64
          modules: qtwebglplugin
      - run: env
        shell: bash
      - run: ${{ env.Qt5_DIR }}/bin/qmake.exe -config release QuteScoop.pro
      - run: make 
      - run: make install
      - working-directory: DIST-win64
        run: ${{ env.Qt5_DIR }}/bin/windeployqt.exe 
      - run: windeployqt DIST-win64
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: QuteScoop-Win-${{ steps.tag.outputs.SOURCE_NAME }}-${{ github.sha }}.zip
          path: ./DIST-win64
